name: Feature Branch

on:
  push:
    branches-ignore:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run tests
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install && npm test
